/* auto-generated by reldoc generate */
import type { DocSchema } from "@reldoc/core";
import schema_prisma_1_0_0 from "../../schemas/schema-prisma-1-0-0.json";
import schema_prisma_2_0_0 from "../../schemas/schema-prisma-2-0-0.json";
import schema_prisma_3_0_0 from "../../schemas/schema-prisma-3-0-0.json";
import schema_prisma_multi_1_0_0 from "../../schemas/schema-prisma-multi-1-0-0.json";
import schema_drizzle_1_0_0 from "../../schemas/schema-drizzle-1-0-0.json";
import schema_drizzle_multi_1_0_0 from "../../schemas/schema-drizzle-multi-1-0-0.json";

export interface SchemaCatalogVersion {
  id: string;
  version: string;
  schema: DocSchema;
}

export interface SchemaCatalogGroup {
  id: string;
  file: string;
  orm: DocSchema["orm"];
  versions: SchemaCatalogVersion[];
}

export const schemaCatalog: SchemaCatalogGroup[] = [
  {
    id: "schema.prisma",
    file: "schema.prisma",
    orm: "prisma",
    versions: [
      {
        id: "schema-prisma-1-0-0",
        version: "v1.0.0",
        schema: schema_prisma_1_0_0 as DocSchema,
      },
      {
        id: "schema-prisma-2-0-0",
        version: "v2.0.0",
        schema: schema_prisma_2_0_0 as DocSchema,
      },
      {
        id: "schema-prisma-3-0-0",
        version: "v3.0.0",
        schema: schema_prisma_3_0_0 as DocSchema,
      }
    ],
  },
  {
    id: "multi-file",
    file: "multi-file",
    orm: "prisma",
    versions: [
      {
        id: "schema-prisma-multi-1-0-0",
        version: "v1.0.0",
        schema: schema_prisma_multi_1_0_0 as DocSchema,
      },
      {
        id: "schema-drizzle-multi-1-0-0",
        version: "v1.0.0",
        schema: schema_drizzle_multi_1_0_0 as DocSchema,
      }
    ],
  },
  {
    id: "schema.ts",
    file: "schema.ts",
    orm: "drizzle",
    versions: [
      {
        id: "schema-drizzle-1-0-0",
        version: "v1.0.0",
        schema: schema_drizzle_1_0_0 as DocSchema,
      }
    ],
  }
];

export const defaultSchemaId = "schema-prisma-1-0-0";
