import { mkdir, readFile, writeFile } from "fs/promises";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const cssPath = resolve(root, "dist/ui/styles.bundled.css");
const outPath = resolve(root, "src/ui/styles-css.ts");
const xyflowCssPath = require.resolve("@xyflow/react/dist/style.css");

const [bundledCss, xyflowCss] = await Promise.all([
    readFile(cssPath, "utf-8"),
    readFile(xyflowCssPath, "utf-8"),
]);

const css = `${xyflowCss}\n${bundledCss}`;
const source = `/* auto-generated by scripts/inline-css.ts — do not edit */
export const OZZYRM_CSS = ${JSON.stringify(css)};
`;

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, source, "utf-8");
console.log(`inlined css → ${outPath} (${css.length} chars)`);
