/**
 * Only allow the exact generate() stamp module shape before dynamic import.
 * Prevents arbitrary JS execution if `.ozzyrm/stamp.js` is overwritten.
 */
const STAMP_MODULE_RE =
    /^\s*(?:\/\*\*[\s\S]*?\*\/\s*)?export\s+const\s+ozzyrmStamp\s*=\s*("[^"\n\\]*(?:\\.[^"\n\\]*)*"|'[^'\n\\]*(?:\\.[^'\n\\]*)*')\s*;?\s*$/;

export function isSafeOzzyrmStampModule(source: string): boolean {
    return STAMP_MODULE_RE.test(source.trim());
}

export function buildOzzyrmStampModule(stamp: string): string {
    return (
        `/** auto-generated by ozzyrm — import to opt into schema HMR */\n` +
        `export const ozzyrmStamp = ${JSON.stringify(stamp)};\n`
    );
}
